### ISSUE TITLE
[Wearable] SnapListStyle / When call scrollToPosition, list is broken.

### ISSUE THREAD

**Issue by HaYoung-Dev** [Samsung/TAU#1237]
i used the SnapListStyle list.
When call scrollToPosition function, list is broken.

**Comment by HunseopJeong** [comment]
@hykim1, Which version are you using?

**Comment by HaYoung-Dev** [comment]
@HunseopJeong tau version is 1.1.8. 
Here is my code. 
precondition : dynamic data

listView = page.querySelector(".ui-listview");
listHelper = tau.helper.SnapListStyle.create(listView, {
 animate: "scale",
 snapListview: false
});								
var snap = listHelper.getSnapList();
snap.scrollToPosition(5);

**Comment by HunseopJeong** [comment]
This issue was fixed by #511.
Could you update your TAU latest?

**Comment by HaYoung-Dev** [comment]
@HunseopJeong The problem is still reproduced... i updated tau 1.1.13.  
Reproduction steps is
1. list created with dynamic data.
2. set scrollToPosition
3. touch scrolled.

**Comment by HunseopJeong** [comment]
@hykim1, Thank you for the report.

`` 1. list created with dynamic data.``
How do you create the list with dynamic data.
If you share your reproduce steps more detail, it help me to resolve the issue.
