### ISSUE TITLE
Timepicker: Bezel changes spinner value even if its inactive

### ISSUE THREAD

**Issue by pkaczmarczy** [Samsung/TAU#445]
Right after building time picker nothing is selected and bezel does not affect anything (that's OK).
After selecting one of the spinners bezel can spin each one correctly, but then if no spinner would be selected rotarydetent events are still handled and inactive spinner changes its value.

The same problem may occur with other spinner based widgets.

**Comment by singa2000** [comment]
@TomaszLukawskiSam ,
Would you confirm the issue was fixed by https://github.com/Samsung/TAU/pull/531?

**Comment by grzegorz-czajkowski** [comment]
I will confirm if #531 fixes this issue.

**Comment by grzegorz-czajkowski** [comment]
I was testing this issue in UI Components App (Controls -> Spin -> Group) and I can not reproduce it. Bezel does not affect spinner value if it's not active (clicked). 
However, #531 does not fix this. I did revert of this PR and spinner still works fine. This was rather fixed by something else.

@lslachciak and @TomaszLukawskiSam I suggest closing this issue.
